version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: flow-sheriff-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: flow-sheriff-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ratelimiter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
